/* Generated By:JavaCC: Do not edit this line. LTLParserConstants.java */
package org.mpi_sws.rltl.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface LTLParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int FOP = 5;
  /** RegularExpression Id. */
  int GOP = 6;
  /** RegularExpression Id. */
  int XOP = 7;
  /** RegularExpression Id. */
  int UOP = 8;
  /** RegularExpression Id. */
  int ROP = 9;
  /** RegularExpression Id. */
  int AND = 10;
  /** RegularExpression Id. */
  int OR = 11;
  /** RegularExpression Id. */
  int IMPL = 12;
  /** RegularExpression Id. */
  int NEG = 13;
  /** RegularExpression Id. */
  int LPAR = 14;
  /** RegularExpression Id. */
  int RPAR = 15;
  /** RegularExpression Id. */
  int ID = 16;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"rF\"",
    "\"rG\"",
    "\"rX\"",
    "\"rU\"",
    "\"rR\"",
    "\"&\"",
    "\"|\"",
    "\"=>\"",
    "\"!\"",
    "\"(\"",
    "\")\"",
    "<ID>",
  };

}
